sudo: required

language: generic

dist: xenial

services:
  - docker

before_install:
  - sudo apt update && sudo apt install -y jq

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd sync_k8s_docker_images && bash main.sh

#deploy:
#  provider: script
#  script: bash docker_push
#  on:
#    branch: master
