sudo: required

language: generic

dist: xenial

env:
  - LANG="zh_CN.UTF-8"

services:
  - docker

before_install:
  - sudo apt update && sudo apt install -y jq curl

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./main.sh
  #- ./main_travis.sh

#deploy:
#  provider: script
#  script: bash docker_push
#  on:
#    branch: master
