sudo: required

language: generic

dist: xenial

env:
  global:
    - LANG="zh_CN.UTF-8"
    - LANGUAGE="zh_CN:zh:en_US:en"

services:
  - docker

before_install:
  - sudo apt update && sudo apt install -y jq curl language-pack-zh-hans

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./main_travis.sh

#deploy:
#  provider: script
#  script: bash docker_push
#  on:
#    branch: master
